name: Build and Deploy

on:
  push:
    branches:
      - main
      
env:
  GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to GitHub Packages
        run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/avansoft/flickit-dsl-editor
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}